[phases.setup]
nixPkgs = [
    "libGL",
    "glib",
    "libgcc", 
    "libstdcxx5",
    "zlib",
    "libpng",
    "libjpeg",
    "libtiff",
]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python detect_server.py"
